name: tom
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy~=1.26.4
      - pandas~=2.2.1
      - opencv-python~=4.7.0.72
      - ffmpeg~=1.4
      - ffmpeg-python~=0.2.0
      - python-vlc~=3.0.20123
      - cherrypy~=18.8.0
      - pynput~=1.7.6
      - pytest~=7.1.3
      - pytest_mock~=3.12.0
      - pytest_cov~=4.1.0
      - pytest_asyncio~=0.23.5
      - pylint~=3.1.0
      - oauthlib~=3.2.2
      - fitbit~=0.3.1
      - websockets~=10.4
      - matplotlib~=3.7.4
      - lxml~=4.9.4
      - tqdm~=4.65.2
      - absl-py~=1.4.0
      - easydict~=1.10
      - pillow~=9.5.0
      - ultralytics==8.0.126
      - supervision~=0.8.0
      - python-dotenv~=1.0.1
      - protobuf~=4.25.3
      - langchain~=0.2.11
      - langchain-google-genai~=1.0.8
      - langchain-openai~=0.1.19
      - langchain_anthropic~=0.1.11
      - roboflow~=1.1.21
      - googlemaps~=4.10.0
      - openrouteservice~=2.3.3
      - geographiclib~=2.0
      - google-cloud-vision~=3.7.1
      - google-cloud-translate~=3.15.2
      - speechrecognition~=3.10.1
      - openai-whisper==20231117
      - tensorflow==2.16.1
      - tensorflow-hub==0.16.1
      - torchaudio==2.1.2
      - torch==2.1.2
      - torchvision==0.16.2
      - transformers~=4.40.1
      - shapely~=2.0.3
      - sqlalchemy~=2.0.27
      - psycopg2~=2.9.9
      - tzdata~=2023.4
      - pyaudio~=0.2.14
      - pysoundfile~=0.9.0
      - shared-memory-dict~=0.7.2
      - fastapi~=0.110.2
      - transformers~= 4.40.1
      - uvicorn~=0.29.0
      - Logbook~=1.7.0
      - python-docx~=1.1.2
