input:
  - name: "websocket"
    entrypoint: "websocket_widget.WebsocketWidget.start"
    exitpoint: ""
    next:
      - "service:running"
service:
  - name: "running"
    entrypoint: "running_service.running_service.RunningService.run"
    exitpoint: ""
    next:
      - "input:websocket|output_send"
